#!/bin/env python3

try:
    import requests
    import socket
    import sys
    import pandas
except Exception as e:
    e = str(e).split("'")[1]
    print("No module named {a}\nTry run this syntax: pip install {a}".format(a=e))
    sys.exit(1)

def banner():
    print(
"""
Usage:
        -h => This message
        -u => Update database""")

def update():
    try:

    except Exception as e:
        print(e)


if __name__ == '__main__':
    helper = ['-u', '-h']
    try:
        if sys.argv[1] == "-u":
            update()
        else:
            banner()
        sys.exit(0)
    except Exception:
        pass
    try:
        print(
"""    ** **
   *******
   *******
 ** ***** **
**** *** ****
***** * *****
 ***********
***** * *****
**** *** ****
 ** ***** **
   *******
   *******
    ** **

By: MrXY ( mrxy@parsect.com )
================
PARSECT PXploit\n""")
        host = str(input("ip/domain> "))
    except KeyboardInterrupt:
        print("\n[!] Exit (Ctrl+C)")
        sys.exit(0)
    except Exception as e:
        e = str(e)
        if "invalid literal" in e:
            print("[!] Your input is invalid!")
            sys.exit(1)
        else:
            print("[-] Something wrong!\n\nReport issue: https://github.com/DwiWardana/pxploit/issues\nEmail me: mrxy@parsect.com")
